name: 'Terraform'

on:
  push:
    branches: 
      - main
  pull_request:

permissions:
  contents: read
defaults:
  run:
    working-directory: terraform-scripts
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      pull-requests: write

    steps:
      - uses: hashicorp/setup-terraform@v2
      
      - name: List files in the directory (after decrypt)
        run: | 
          pwd
      - name: List files in the directory (after decrypt)
        run: | 
          ls .
      
      - name: Terraform Init
        id: init
        run: terraform init
