name: 'Terraform'

on:
  push:
    branches: 
      - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      pull-requests: write
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform-scripts
    
    steps:
      #  Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        
      - name: Terraform Plan
        run: terraform plan -input=false
      
      - name: Terraform Apply
        env:
          GITHUB_TOKEN: ${{ secrets.TKN }}
        run: terraform apply -auto-approve -input=false
