name: 'Terraform'

on:
  push:
    branches: 
      - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      pull-requests: write
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform-scripts
    
    steps:
      - uses: hashicorp/setup-terraform@v2
      
      - name: PWD in directory
        run: | 
          pwd
          
      - name: List files in the directory
        run: | 
          ls .
      
      - name: Terraform Init
        id: init
        run: terraform init
